/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a tracked Playlist from its public URL. */
        post: operations["createPlaylist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePlaylistRequest: {
            /**
             * @description The playlist's public URL on its Source.
             * @example https://open.spotify.com/playlist/3cEYpjA9oz9GiPac4AsH4n
             */
            url: string;
        };
        /**
         * @description The shared error envelope. Every error response on every endpoint uses
         *     it. `message` is written for a human and printed verbatim by the CLI, so
         *     the copy can improve without a client release; `code` is what the CLI
         *     branches on.
         */
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                message: string;
            };
        };
        /**
         * @description Stable, machine-readable. Grows as endpoints are added: `playlist_gone`
         *     and `source_unavailable` arrive with the responses that emit them.
         * @enum {string}
         */
        ErrorCode: "invalid_url";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createPlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlaylistRequest"];
            };
        };
        responses: {
            /** @description No Source adapter claims this URL. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
