/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a tracked Playlist from its public URL.
         * @description Nothing is read from the Source here. The Playlist is recorded and the
         *     caller gets an id back immediately; Resolution happens out of band,
         *     which is what keeps upstream usage proportional to Playlists rather
         *     than to callers.
         *
         *     Re-adding a Playlist already tracked is harmless and returns the same
         *     id: the id is derived from the URL, so no lookup decides this.
         */
        post: operations["createPlaylist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The Tracks of a Playlist, as its Source describes them.
         * @description One call answers both "is it ready" and "here they are", so the CLI's
         *     poll loop and its fetch are the same request.
         */
        get: operations["getPlaylistTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePlaylistRequest: {
            /**
             * @description The playlist's public URL on its Source.
             * @example https://open.spotify.com/playlist/3cEYpjA9oz9GiPac4AsH4n
             */
            url: string;
        };
        CreatePlaylistResponse: {
            id: components["schemas"]["PlaylistId"];
            status: components["schemas"]["PlaylistStatus"];
        };
        /**
         * @description A Playlist's Tracks at one Version. The same document is what the server
         *     stores, so the bytes served are the bytes written.
         */
        PlaylistTracks: {
            /**
             * @description The Playlist's Version, and the ETag this answer carries. It moves
             *     whenever the Playlist's contents change, and it is the whole of the
             *     client's "am I current?".
             */
            version: number;
            /**
             * @description How many entries the Source offered that are not Tracks -- podcast
             *     episodes, local files, entries it will no longer serve. They are
             *     left out of `tracks`, and counted here so that a shorter list than
             *     the Source shows does not read as data loss.
             */
            skipped: number;
            tracks: components["schemas"]["Track"][];
        };
        /**
         * @description An entry in a Playlist as its Source describes it. Metadata, never a
         *     file.
         */
        Track: {
            /** @description The Track's id within its Source. */
            sourceTrackId: string;
            title: string;
            /** @description Always an array, including when there is one artist. */
            artists: string[];
            album: string | null;
            durationMs: number | null;
            /**
             * @description The recording's ISRC when the Source exposes one. Matching's
             *     strongest signal, carried now so Matching needs no re-read later.
             */
            isrc: string | null;
            /**
             * @description The Source's own index for this entry, kept as it is. Skipped
             *     entries therefore leave visible gaps rather than renumbering what
             *     follows them.
             */
            position: number;
            /**
             * @description The largest cover image the Source offers, destined for file tags.
             *     Downscaling later is possible where upscaling is not.
             */
            coverImageUrl: string | null;
        };
        /**
         * @description Deliberately not an empty track list: a Playlist with no Tracks yet and
         *     a Playlist that resolved to nothing are different answers, and a client
         *     that cannot tell them apart stops polling too early.
         */
        PendingTracks: {
            /** @constant */
            status: "pending";
        };
        /**
         * @description The Source name and the Playlist's id within that Source, joined by a
         *     colon. Deterministic, which is what makes creating a Playlist
         *     idempotent without a lookup. See docs/adr/0001-namespaced-playlist-ids.md.
         * @example spotify:3cEYpjA9oz9GiPac4AsH4n
         */
        PlaylistId: string;
        /**
         * @description Where a Playlist is in its lifecycle, in the vocabulary of `CONTEXT.md`.
         *     Grows as the responses that emit them arrive. The Tracks response
         *     carries a Version rather than a status, so `ok` waits for the answer
         *     that names one -- creating a Playlist already resolved -- and
         *     `unreachable` and `gone` for the failure states.
         * @enum {string}
         */
        PlaylistStatus: "pending";
        /**
         * @description The shared error envelope. Every error response on every endpoint uses
         *     it. `message` is written for a human and printed verbatim by the CLI, so
         *     the copy can improve without a client release; `code` is what the CLI
         *     branches on.
         */
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                message: string;
            };
        };
        /**
         * @description Stable, machine-readable. Grows as endpoints are added: `playlist_gone`
         *     and `source_unavailable` arrive with the failure states.
         * @enum {string}
         */
        ErrorCode: "invalid_url" | "playlist_not_found";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createPlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlaylistRequest"];
            };
        };
        responses: {
            /** @description Tracked. Resolution has not run yet, so there are no Tracks. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePlaylistResponse"];
                };
            };
            /** @description No Source adapter claims this URL. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPlaylistTracks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["PlaylistId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Tracks of the Playlist, as of the Version naming this snapshot. */
            200: {
                headers: {
                    /**
                     * @description The Playlist's Version, quoted. Strong, because it names an
                     *     immutable snapshot exactly rather than an equivalent one. Send
                     *     it back as `If-None-Match` on the next sync.
                     */
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistTracks"];
                };
            };
            /**
             * @description Resolution has not completed, so the Playlist has no Tracks yet.
             *     This is the poll response: ask again.
             */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingTracks"];
                };
            };
            /**
             * @description Nothing is tracking a Playlist under this id. Ids are derived from
             *     the URL, so this is a Playlist that was never added -- not one whose
             *     Resolution failed, which has its own answers.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
