/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a tracked Playlist from its public URL.
         * @description Nothing is read from the Source here. The Playlist is recorded and the
         *     caller gets an id back immediately; Resolution happens out of band,
         *     which is what keeps upstream usage proportional to Playlists rather
         *     than to callers.
         *
         *     Re-adding a Playlist already tracked is harmless and returns the same
         *     id: the id is derived from the URL, so no lookup decides this.
         */
        post: operations["createPlaylist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The Tracks of a Playlist, as its Source describes them.
         * @description One call answers both "is it ready" and "here they are", so the CLI's
         *     poll loop and its fetch are the same request.
         */
        get: operations["getPlaylistTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePlaylistRequest: {
            /**
             * @description The playlist's public URL on its Source.
             * @example https://open.spotify.com/playlist/3cEYpjA9oz9GiPac4AsH4n
             */
            url: string;
        };
        CreatePlaylistResponse: {
            id: components["schemas"]["PlaylistId"];
            status: components["schemas"]["PlaylistStatus"];
        };
        /**
         * @description A Playlist's Tracks at one Version. The same document is what the server
         *     stores, so the bytes served are the bytes written.
         */
        PlaylistTracks: {
            /**
             * @description The Playlist's Version, and the ETag this answer carries. It moves
             *     whenever the Playlist's contents change, and it is the whole of the
             *     client's "am I current?".
             */
            version: number;
            /**
             * @description The Playlist's own name on its Source. `null` where the Source
             *     offers none, or offers one that is only whitespace: a Playlist
             *     with no usable name is served without one rather than under an
             *     invented placeholder, which a client cannot tell from a real name.
             */
            title: string | null;
            /**
             * @description How many entries the Source offered that are not Tracks -- podcast
             *     episodes, local files, entries it will no longer serve. They are
             *     left out of `tracks`, and counted here so that a shorter list than
             *     the Source shows does not read as data loss.
             */
            skipped: number;
            tracks: components["schemas"]["Track"][];
        };
        /**
         * @description An entry in a Playlist as its Source describes it. Metadata, never a
         *     file.
         */
        Track: {
            /** @description The Track's id within its Source. */
            sourceTrackId: string;
            title: string;
            /** @description Always an array, including when there is one artist. */
            artists: string[];
            album: string | null;
            durationMs: number | null;
            /**
             * @description The recording's ISRC when the Source exposes one. Matching's
             *     strongest signal, carried now so Matching needs no re-read later.
             */
            isrc: string | null;
            /**
             * @description The Source's own index for this entry, kept as it is. Skipped
             *     entries therefore leave visible gaps rather than renumbering what
             *     follows them.
             */
            position: number;
            /**
             * @description The largest cover image the Source offers, destined for file tags.
             *     Downscaling later is possible where upscaling is not.
             */
            coverImageUrl: string | null;
        };
        /**
         * @description Deliberately not an empty track list: a Playlist with no Tracks yet and
         *     a Playlist that resolved to nothing are different answers, and a client
         *     that cannot tell them apart stops polling too early.
         */
        PendingTracks: {
            /** @constant */
            status: "pending";
        };
        /**
         * @description The Source name and the Playlist's id within that Source, joined by a
         *     colon. Deterministic, which is what makes creating a Playlist
         *     idempotent without a lookup. See docs/adr/0001-namespaced-playlist-ids.md.
         * @example spotify:3cEYpjA9oz9GiPac4AsH4n
         */
        PlaylistId: string;
        /**
         * @description Where a Playlist is in its lifecycle, in the vocabulary of `CONTEXT.md`,
         *     as far as an answer carrying one can say.
         *
         *     These two and no more. `CONTEXT.md` also names Unreachable and Gone, and
         *     neither will appear here: a Playlist in either state has no Tracks to
         *     serve, so it is answered with an error envelope and a code the client
         *     branches on -- `source_unavailable` and `playlist_gone` -- rather than
         *     with a success body describing a state. A status says "here, or nearly
         *     here"; a code says "not coming, and why".
         * @enum {string}
         */
        PlaylistStatus: "pending" | "ok";
        /**
         * @description The shared error envelope. Every error response on every endpoint uses
         *     it. `message` is written for a human and printed verbatim by the CLI, so
         *     the copy can improve without a client release; `code` is what the CLI
         *     branches on.
         */
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                message: string;
            };
        };
        /**
         * @description Stable, machine-readable, and what the CLI branches on. Each says what
         *     the caller should do next: correct the address, add the Playlist first,
         *     stop tracking it, or try again later.
         *
         *     Four things to do and five codes, because the last two share a status and say different things about where the
         *     fault is. `source_unavailable` is about a Playlist's Source, and a
         *     client is right to record the Playlist as unreachable on it;
         *     `snapshot_unavailable` is about this service, and says nothing about the
         *     Playlist at all -- a client that treated it as the Source's failure
         *     would be recording something untrue.
         * @enum {string}
         */
        ErrorCode: "invalid_url" | "playlist_not_found" | "playlist_gone" | "source_unavailable" | "snapshot_unavailable";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createPlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlaylistRequest"];
            };
        };
        responses: {
            /**
             * @description Tracked, and already resolved. The caller can fetch its Tracks
             *     immediately rather than polling for a Resolution that has happened.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePlaylistResponse"];
                };
            };
            /** @description Tracked. Resolution has not run yet, so there are no Tracks. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePlaylistResponse"];
                };
            };
            /** @description No Source adapter claims this URL. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Tracked, and its Source refuses it. The same answer the Tracks
             *     endpoint gives, so a caller never has to poll to learn a state that
             *     will not change.
             */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Tracked, and its Source could not be read for a reason believed
             *     temporary. Nothing is asked of the Source here; the Resolution that
             *     failed is either still being retried or has been set aside.
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPlaylistTracks: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description The Version the caller already holds, quoted -- the ETag off the
                 *     answer it last stored. Declared because it is the request that makes
                 *     the 304 below the overwhelmingly common answer rather than a rare
                 *     one, and a response nothing in the document asks for reads as one
                 *     nothing ever gets.
                 *
                 *     Absent from an ask by a caller holding nothing: a Playlist it has
                 *     never seen resolved has no Version to send.
                 */
                "If-None-Match"?: string;
            };
            path: {
                id: components["schemas"]["PlaylistId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Tracks of the Playlist, as of the Version naming this snapshot. */
            200: {
                headers: {
                    /**
                     * @description The Playlist's Version, quoted. Strong, because it names an
                     *     immutable snapshot exactly rather than an equivalent one. Send
                     *     it back as `If-None-Match` on the next sync.
                     */
                    ETag: string;
                    /**
                     * @description `no-cache`: hold this answer, but revalidate before using it.
                     *     Without it a shared cache may apply heuristic freshness and
                     *     stop revalidating, at which point a Version that moves never
                     *     reaches the client at all.
                     */
                    "Cache-Control": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistTracks"];
                };
            };
            /**
             * @description Resolution has not completed, so the Playlist has no Tracks yet.
             *     This is the poll response: ask again.
             */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingTracks"];
                };
            };
            /**
             * @description The `If-None-Match` sent matches the current Version, so the caller
             *     already holds this answer and none is sent. This is the sync that
             *     should be overwhelmingly the most common one: serving it reads a
             *     single cache key and touches no database.
             */
            304: {
                headers: {
                    /** @description The Version the caller was found to be holding, quoted. */
                    ETag: string;
                    /** @description `no-cache`, as on the 200 this revalidates. */
                    "Cache-Control": string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Nothing is tracking a Playlist under this id. Ids are derived from
             *     the URL, so this is a Playlist that was never added -- not one whose
             *     Resolution failed, which has its own answers.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description The Source will not serve this Playlist and retrying will not help
             *     -- it was deleted, made private, or is curated by the Source itself
             *     and closed to other apps. The Source does not distinguish the three,
             *     so neither does this, and the message names the likely causes.
             *
             *     Only for a Playlist that never resolved. One that has Tracks goes on
             *     being served them, at the Version it last reached, however its Source
             *     has answered since: a remote failure never costs a caller what it
             *     already had. `POST /playlists` still answers `410` for it, and the
             *     two are not in conflict -- the Source will not serve that Playlist
             *     again, and these are the Tracks from when it did.
             */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description No Tracks to serve, for a reason believed temporary. Two of them,
             *     told apart by the code rather than by the status: `source_unavailable`
             *     is a Resolution that failed and has none yet, and
             *     `snapshot_unavailable` is a Playlist whose Tracks exist and cannot be
             *     assembled just now. Worth asking again either way.
             *
             *     `source_unavailable` carries the same rule as the `410` above: a
             *     Playlist that has Tracks is served them rather than this.
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
