import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

/**
 * Writes the wordmark into the two files that ship it, from the banner at the
 * top of `docs/design/DESIGN.md`.
 *
 * **The script that `docs/design/SITE.md` 03 has always described.** That section
 * said the constant "is generated by script rather than retyped -- hand-copying
 * has already dropped them once", and named the extraction as fence-delimited
 * rather than line-numbered. No such script existed; #60 is the ticket that
 * noticed, and this is it. The claim was load-bearing in the way a false claim
 * usually is: a reader who hit the old two-copy check went looking for the
 * generator and found nothing.
 *
 * **One source, and it is the document rather than either copy.** Both shipping
 * files already name the banner as where their art came from, so making it the
 * real source moves nothing -- it only stops the naming being aspirational.
 * `schema/` was rejected for the same art in #50 and is still the wrong home:
 * that package is the client/server contract, and a piece of art is not that.
 *
 * **Generated, then diffed, rather than compared.** `cli/scripts/check-wordmark.ts`,
 * deleted alongside this file being written, held two copies up against each
 * other -- which could only ever police drift after the fact, and could not
 * catch two copies that drifted *together* without a per-file assertion to lean
 * on. CI now regenerates and runs `git diff --exit-code`, the shape
 * `worker.yml` already uses for `schema/src/generated.ts`. A copy that no
 * longer matches its source is a diff rather than a comparison nobody ran.
 *
 * **It reads bytes and never imports, which the check it replaces explained
 * best.** ECMAScript normalises CRLF to LF inside a template literal when the
 * file is parsed, so two modules whose bytes differ hand back identical
 * strings. An importing generator would agree with itself on a Windows checkout
 * and on a Linux one while the files on disk disagreed -- and a carriage return
 * is exactly what the `eol=lf` pins in `.gitattributes` keep out of art that is
 * measured in columns. Reading bytes also keeps the workspaces apart: an
 * `import` across them would pull a site source file into the CLI's typecheck
 * program for a string neither program compiles against.
 *
 * Here rather than at the repo root, though it writes into two workspaces and
 * belongs to neither. `cli.yml` already says why a check spanning both runs in
 * one of them, and this is where the check it replaces lived. The deciding
 * reason is narrower: `cli/tsconfig.json` includes every `.ts` file under
 * `scripts/`, so a script in this directory is typechecked by
 * `bun run --cwd cli typecheck` and one at the repo root is typechecked by
 * nothing -- there is no root `tsconfig.json`, and no root `devDependencies` to
 * give one types.
 *
 * (Written out rather than as the glob `cli/tsconfig.json` actually holds,
 * because that glob closes a block comment three characters in.)
 */

/** The one source, and the two files generated from it. */
const SOURCE = 'docs/design/DESIGN.md'
const SITE = 'site/lib/content.ts'
const CLI = 'cli/src/wordmark.ts'

/** Resolved against this file rather than the cwd, so where it is run from does not matter. */
const at = (repoPath: string): string =>
  fileURLToPath(new URL(`../../${repoPath}`, import.meta.url))

/**
 * Annotated on the binding rather than on the arrow, which is not a style
 * choice. TypeScript narrows after a call only when the *variable* is typed as
 * returning `never`, so with the return type on the arrow alone every bare
 * `fail(...)` below would leave the code after it reachable -- and the reader
 * would be handed a non-null assertion to paper over it.
 */
const fail: (...lines: string[]) => never = (...lines) => {
  for (const line of lines) console.error(line)
  process.exit(1)
}

/**
 * How both copies declare it, character for character.
 *
 * Anchoring on the declaration rather than on a line number is what lets either
 * file grow above the wordmark without moving it.
 */
const OPENS = 'export const WORDMARK = `'

/** What opens and closes the banner in the document. */
const FENCE = '```'

/**
 * One empty row, then the art.
 *
 * The blank is #68's, and it is part of the banner so that the art and the room
 * above it travel together -- a surface that wanted the mark would otherwise
 * have to remember the gap. Two surfaces still decide for themselves, and
 * neither is the art: `header.ts` gives the narrow *word* a matching row, and
 * the site's session module promotes this one into a line of its own, which is
 * what a terminal shows and what keeps the art it hands a `<pre>` from opening
 * with a newline the browser would swallow.
 *
 * It is exempt from the width below and cannot be anything but empty: a row of
 * 67 spaces would satisfy both rules while being exactly the trailing
 * whitespace every file here warns about, and the first editor to save the
 * document would silently take it away again.
 */
const BLANK_ROWS = 1
const ART_ROWS = 5
const ROWS = BLANK_ROWS + ART_ROWS
const COLUMNS = 67

/**
 * A space, or the Block Elements block.
 *
 * A range rather than the five glyphs the art happens to use today, because
 * U+2596 is perfectly good art and a rule that refused it would only teach
 * people to edit this file. It is also what makes the column count mean
 * anything: every code point this admits is in the BMP, so one UTF-16 unit is
 * one character is one column, and counting and indexing agree.
 */
const BLOCKS = /^[ ▀-▟]*$/

/** A trailing space and a row that has ended look identical every other way. */
const point = (character: string): string =>
  `U+${character.codePointAt(0)!.toString(16).toUpperCase().padStart(4, '0')}`

const read = (where: string): string => {
  try {
    return readFileSync(at(where), 'utf8')
  } catch {
    return fail(`${where} is not there.`)
  }
}

/**
 * The banner, taken from the first fence in the document.
 *
 * Fence-delimited rather than line-numbered, which is what SITE.md promised and
 * what lets the prose above the banner grow without moving anything.
 *
 * Carriage returns are dropped on the way in. `DESIGN.md` is checked out CRLF
 * today and every row of this art is measured in columns, so a carriage return
 * would be a byte on the end of every one of them that nobody can see. The
 * `.gitattributes` pin says the same thing to git; this says it to the one
 * reader that would otherwise carry them into two files pinned against them.
 */
const banner = (): string[] => {
  const lines = read(SOURCE).replace(/\r\n/g, '\n').split('\n')

  const opens = lines.findIndex((line) => line.trimEnd() === FENCE)
  if (opens === -1) {
    return fail(
      `${SOURCE} has no fenced block, so there is no wordmark to read out of it.`,
      'The banner is the first fence in the document, and it is the source both',
      'shipping copies are written from.',
    )
  }

  const closes = lines.findIndex((line, index) => index > opens && line.trimEnd() === FENCE)
  if (closes === -1) {
    return fail(`${SOURCE} opens a fence at line ${opens + 1} and never closes it.`)
  }

  return lines.slice(opens + 1, closes)
}

/**
 * The banner, checked before a single byte of it is written anywhere.
 *
 * These are `check-wordmark.ts`'s per-file assertions, moved rather than
 * dropped. They were the half of that check which caught two copies drifting
 * *together* -- both rewritten CRLF, or both run through something that trims
 * trailing whitespace -- which an equality check alone sails straight past. A
 * generator has one file to make those assertions about instead of two, and
 * makes them at the only moment they still matter: before it propagates
 * whatever it found.
 */
const checked = (rows: string[]): string[] => {
  if (rows.length !== ROWS) {
    fail(
      `${SOURCE} has ${rows.length} row(s) of wordmark, and must have ${ROWS}:`,
      `one blank row and then ${ART_ROWS} of art. The art is a rectangle, and anything`,
      'else is a handful of ragged strings.',
    )
  }

  // Split off rather than skipped inside the loop, so the width rule below has
  // nothing to except and reads as the flat statement it is.
  const [blank, ...art] = rows

  if (blank !== '') {
    fail(
      `${SOURCE}'s wordmark opens with ${[...blank].length} column(s), and must open with an empty row.`,
      'The blank above the art is part of the banner. Spaces would read the same here',
      'and be taken by the first thing that trims trailing whitespace.',
    )
  }

  for (const [offset, row] of art.entries()) {
    const index = offset + BLANK_ROWS

    // Before the width, because it is what lets the width be counted this way.
    if (!BLOCKS.test(row)) {
      const stray = [...row].find((character) => !BLOCKS.test(character))!
      fail(
        `${SOURCE} row ${index + 1} contains ${point(stray)}, which this art is not built from.`,
        'It is spaces and Block Elements (U+2580-U+259F) and nothing else, because those',
        'are what a terminal font and an unsubsetted webfont can both be relied on to',
        'carry. A glyph outside them fails silently, on a machine that is not this one.',
      )
    }

    if ([...row].length !== COLUMNS) {
      fail(
        `${SOURCE} row ${index + 1} is ${[...row].length} columns, and must be ${COLUMNS}.`,
        'Rows that do not measure the same shear the letterforms apart. Two of them end',
        'in a space that anything trimming trailing whitespace will take, and that is',
        'usually what happened.',
      )
    }
  }

  const whole = rows.join('\n')

  // What a template literal cannot hold without the file and the string
  // becoming two different things.
  if (whole.includes('${') || whole.includes('\\') || whole.includes('`')) {
    fail(
      `${SOURCE}'s banner holds a backtick, a backslash or a substitution.`,
      'The art has to survive being pasted into a template literal unchanged.',
    )
  }

  return rows
}

/**
 * What one file should contain, with the bytes between its declaration and the
 * backtick that closes it replaced -- or nothing, where it already says this.
 *
 * Spliced rather than written whole, because neither target is only the art:
 * `site/lib/content.ts` also holds the install commands and the hero copy, and
 * both carry docblocks that say more than this script knows.
 *
 * It computes and does not write, which is the whole reason it is separate from
 * the loop below. Validating each target as it was written meant a second file
 * whose declaration had been renamed left the first already rewritten -- a run
 * that failed and changed the tree anyway, which is the one outcome a generator
 * guarded by `git diff --exit-code` must not have.
 */
const spliced = (where: string, art: string): string | undefined => {
  const source = read(where)
  const declared = source.split(OPENS).length - 1

  if (declared !== 1) {
    return fail(
      declared === 0
        ? `${where} does not declare the wordmark.`
        : `${where} declares the wordmark ${declared} times, and must declare it once.`,
      `This script finds the art by reading: ${OPENS}`,
      'Renaming the constant, annotating its type, or reformatting the declaration',
      'all hide it from here. Update OPENS in this script alongside whichever it was.',
    )
  }

  const from = source.indexOf(OPENS) + OPENS.length
  const closes = source.indexOf('`', from)
  if (closes === -1) {
    return fail(
      `${where} opens the wordmark and never closes it.`,
      'The literal has to close on the same line the art ends on, which is how the',
      'bytes between the two backticks are known to be all of it.',
    )
  }

  // Nothing to write where nothing changed, so a second run is silent and the
  // report below can say which files actually moved.
  if (source.slice(from, closes) === art) return undefined

  return source.slice(0, from) + art + source.slice(closes)
}

const art = checked(banner()).join('\n')

// Every target located and checked before any of them is written. Both halves
// of that matter: the source is validated by `checked` above, and the shape of
// each file this writes into is validated here -- so a run that is going to
// fail has failed before the first byte lands.
const splices = [SITE, CLI]
  .map((where) => ({ where, text: spliced(where, art) }))
  .filter((one): one is { where: string; text: string } => one.text !== undefined)

for (const { where, text } of splices) writeFileSync(at(where), text)

const shape = `a blank row and ${ART_ROWS} of ${COLUMNS}`

console.log(
  splices.length === 0
    ? `${SITE} and ${CLI} already carry ${SOURCE}'s wordmark: ${shape}.`
    : `Wrote ${SOURCE}'s wordmark into ${splices.map((one) => one.where).join(' and ')}: ${shape}.`,
)
